vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: integrated-puphpet/ubuntu-16.04
                box_url: http://www.integratedfordevelopers.com/integrated-puphpet-0.8-ubuntu-16.04-x64-5.box
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_zt1jolgy2kuu:
                        id: integrated
                        hostname: integrated-standard.localhost.integratedfordevelopers.com
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_6awdtda6ndma:
                                    host: '8080'
                                    guest: '80'
                                vflmnfp_94uiaa86wrsa:
                                    host: '8443'
                                    guest: '443'
                                vflmnfp_jsdfhjhsdkds:
                                    host: '3306'
                                    guest: '3306'
                                vflmnfp_s2kw3om0o2fl:
                                    host: '8025'
                                    guest: '8025'
                                vflmnfp_fjisdidjgldr:
                                    host: '27017'
                                    guest: '27017'
                        memory: '2048'
                        cpus: '4'
        provision:
            puppet:
                manifests_path: vendor/integrated/puphpet/puppet/manifests
                module_path:
                    - vendor/integrated/puphpet/puppet/modules
                    - vendor/integrated/puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_pz96jpwr27qi:
                owner: vagrant
                group: vagrant
                source: ./
                target: /vagrant
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - htop
        - git
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - aa_DJ.UTF-8
            - af_ZA.UTF-8
            - an_ES.UTF-8
            - ar_AE.UTF-8
            - ar_BH.UTF-8
            - ar_DZ.UTF-8
            - ar_EG.UTF-8
            - ar_IQ.UTF-8
            - ar_JO.UTF-8
            - ar_KW.UTF-8
            - ar_LB.UTF-8
            - ar_LY.UTF-8
            - ar_MA.UTF-8
            - ar_OM.UTF-8
            - ar_QA.UTF-8
            - ar_SA.UTF-8
            - ar_SD.UTF-8
            - ar_SY.UTF-8
            - ar_TN.UTF-8
            - ar_YE.UTF-8
            - ast_ES.UTF-8
            - be_BY.UTF-8
            - bg_BG.UTF-8
            - br_FR.UTF-8
            - bs_BA.UTF-8
            - ca_AD.UTF-8
            - ca_ES.UTF-8
            - ca_ES.UTF-8@valencia
            - ca_FR.UTF-8
            - ca_IT.UTF-8
            - cs_CZ.UTF-8
            - cy_GB.UTF-8
            - da_DK.UTF-8
            - de_AT.UTF-8
            - de_BE.UTF-8
            - de_CH.UTF-8
            - de_DE.UTF-8
            - de_LI.UTF-8
            - de_LU.UTF-8
            - el_GR.UTF-8
            - el_CY.UTF-8
            - en_AU.UTF-8
            - en_BW.UTF-8
            - en_CA.UTF-8
            - en_DK.UTF-8
            - en_GB.UTF-8
            - en_HK.UTF-8
            - en_IE.UTF-8
            - en_NZ.UTF-8
            - en_PH.UTF-8
            - en_SG.UTF-8
            - en_US.UTF-8
            - en_ZA.UTF-8
            - en_ZW.UTF-8
            - eo.UTF-8
            - eo_US.UTF-8
            - es_AR.UTF-8
            - es_BO.UTF-8
            - es_CL.UTF-8
            - es_CO.UTF-8
            - es_CR.UTF-8
            - es_DO.UTF-8
            - es_EC.UTF-8
            - es_ES.UTF-8
            - es_GT.UTF-8
            - es_HN.UTF-8
            - es_MX.UTF-8
            - es_NI.UTF-8
            - es_PA.UTF-8
            - es_PE.UTF-8
            - es_PR.UTF-8
            - es_PY.UTF-8
            - es_SV.UTF-8
            - es_US.UTF-8
            - es_UY.UTF-8
            - es_VE.UTF-8
            - et_EE.UTF-8
            - eu_ES.UTF-8
            - eu_FR.UTF-8
            - fi_FI.UTF-8
            - fo_FO.UTF-8
            - fr_BE.UTF-8
            - fr_CA.UTF-8
            - fr_CH.UTF-8
            - fr_FR.UTF-8
            - fr_LU.UTF-8
            - ga_IE.UTF-8
            - gd_GB.UTF-8
            - gl_ES.UTF-8
            - gv_GB.UTF-8
            - he_IL.UTF-8
            - hr_HR.UTF-8
            - hsb_DE.UTF-8
            - hu_HU.UTF-8
            - id_ID.UTF-8
            - is_IS.UTF-8
            - it_CH.UTF-8
            - it_IT.UTF-8
            - iw_IL.UTF-8
            - ja_JP.UTF-8
            - ka_GE.UTF-8
            - kk_KZ.UTF-8
            - kl_GL.UTF-8
            - ko_KR.UTF-8
            - ku_TR.UTF-8
            - kw_GB.UTF-8
            - lg_UG.UTF-8
            - lt_LT.UTF-8
            - lv_LV.UTF-8
            - mg_MG.UTF-8
            - mi_NZ.UTF-8
            - mk_MK.UTF-8
            - ms_MY.UTF-8
            - mt_MT.UTF-8
            - nb_NO.UTF-8
            - nl_BE.UTF-8
            - nl_NL.UTF-8
            - nn_NO.UTF-8
            - oc_FR.UTF-8
            - om_KE.UTF-8
            - pl_PL.UTF-8
            - pt_BR.UTF-8
            - pt_PT.UTF-8
            - ro_RO.UTF-8
            - ru_RU.UTF-8
            - ru_UA.UTF-8
            - sk_SK.UTF-8
            - sl_SI.UTF-8
            - so_DJ.UTF-8
            - so_KE.UTF-8
            - so_SO.UTF-8
            - sq_AL.UTF-8
            - st_ZA.UTF-8
            - sv_FI.UTF-8
            - sv_SE.UTF-8
            - tg_TJ.UTF-8
            - th_TH.UTF-8
            - tl_PH.UTF-8
            - tr_CY.UTF-8
            - tr_TR.UTF-8
            - uk_UA.UTF-8
            - uz_UZ.UTF-8
            - wa_BE.UTF-8
            - xh_ZA.UTF-8
            - yi_US.UTF-8
            - zh_CN.UTF-8
            - zh_HK.UTF-8
            - zh_SG.UTF-8
            - zh_TW.UTF-8
            - zu_ZA.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_aat3nmbcah5o:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                nxvl_yv49kxip1050:
                    www_root: /var/www/awesome/web
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    index_files:
                        - index.html
                        - index.php
                        - app.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                        - /app.php$is_args$args
                nxvl_kqz1aju1xfko:
                    www_root: /var/www/awesome/web
                    location: '~ ^/(app_dev|config)\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /app_dev.php$is_args$args
                    set:
                        - '$path_info $fastcgi_path_info'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: app_dev.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'APP_ENV dev'
                nxvl_c9e3hc6tmivs:
                    www_root: /var/www/awesome/web
                    location: '~ ^/index\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    set:
                        - '$path_info $fastcgi_path_info'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                nxvl_o7z85gfupgul:
                    www_root: /var/www/awesome/web
                    location: '~ ^/app\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /app.php$is_args$args
                    set:
                        - '$path_info $fastcgi_path_info'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: app.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'APP_ENV prod'
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_mk2dj1guqjdm:
            servername: localhost.integratedfordevelopers.com
            serveraliases:
                - localhost
            docroot: /vagrant/web
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                php_html:
                    provider: directory
                    path: /vagrant/web
                    directoryindex: 'index.php index.html'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                php_php:
                    provider: filesmatch
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
        av_1uefcjgy8ezx:
            servername: localhost.e-active.nl
            serveraliases:
                - localhost
            docroot: /vagrant/web
            port: '443'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                php_html:
                    provider: directory
                    path: /vagrant/web
                    directoryindex: 'index.php index.html'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                php_php:
                    provider: filesmatch
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
letsencrypt:
    install: '1'
    settings:
        email: ''
        webserver_service: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - xml
            - gd
            - curl
            - apc
            - mbstring
            - zip
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        max_execution_time: '3600'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_h9neo34wzx5n:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: vagrant
                group: vagrant
                pm: static
                pm.max_children: '4'
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.max_nesting_level: '250'
        xdebug.var_display_max_depth: '8'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '0'
        xdebug.remote_host: 10.0.2.2
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
wpcli:
    install: '0'
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_t1cqp7d6qwdu:
            default: '1'
            bundler: '1'
            version: '2.4'
            gems:
                - deep_merge@1.0.1
                - activesupport
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '7'
    npm_packages:
        - bower
        - less@1.7.5
        - uglify-js
        - uglifycss
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: root
        override_options: {  }
    users:
        mariadbnu_rsmhr7uegmlq:
            name: integrated
            password: integrated
    databases:
        mariadbnd_gblxs6690mla:
            name: integrated
            collate: 'utf8_general_ci'
            sql: ''
    grants:
        mariadbng_orjvkjrp1neo:
            user: integrated
            table: 'integrated.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    users:
        mysqlnu_3wyq7ubgw0ep:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_wbwkn6dluyky:
            name: dbname
            collate: ''
            sql: ''
    grants:
        mysqlng_1zqzhogr5xiw:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 3.4.10
    databases:
        mongodbnuad_p7zh0l4cakkm:
            name: integrated
            user: integrated
            password: integrated
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_x1f7gw0x5qqo:
            name: es-01

